@startuml
'https://plantuml.com/sequence-diagram
autonumber

participant "LM Server" as server order 0
participant LM1 order 1

activate LM1

LM1 -> LM1 : Setup and Start OPC Server
activate LM1
LM1 -> server ** : create
LM1 -> server : add user certificates
activate server
server --> LM1
deactivate server
LM1 -> server : configure network settings
activate server
server --> LM1
deactivate server
LM1 -> server : register namespace
activate server
server --> LM1
deactivate server
LM1 -> server : create data structure\n for RTU data
activate server
server --> LM1
deactivate server
LM1 -> server : create data structure\n for Usage data
activate server
server --> LM1
deactivate server
LM1 -> server : create UA method\n for registering NMs
activate server
server --> LM1
deactivate server
LM1 -> server : create custom event\n type for req violations
activate server
server --> LM1
deactivate server
LM1 -> server : create custom event\n type for general logging
activate server
server --> LM1
deactivate server
LM1 -> server : create custom event\n type for heartbeat
activate server
server --> LM1
deactivate server
LM1 -> server : run server
activate server
'LM1 -> server :
deactivate LM1
@enduml